In [116]:
import numpy as np
import pandas as pd

In [117]:
reci=pd.read_csv('recipe-1.csv')

In [118]:
reci.head()

Recipe_name Author             Date_published  \
0  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
1  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
2  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
3  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
4  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   

  Category      Cuisine Prep_time Cook_time     Serving   Yield Nutrition  \
0   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   
1   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   
2   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   
3   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   
4   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   

  Quantity            Unit               Ingredient  
0    ['2']  ['tablespoon']              ['walnuts']  
1    ['3']     ['Numbers']        ['spring onions']  
2    ['1']  ['tablespoon']   ['white wine vinegar']  
3    ['1']     ['handful']   ['lettuce loose-leaf']  
4  ['1/4']    ['teaspoon']  ['garam masala powder']

In [119]:
reci.Author.value_counts()

TNN    36735
Name: Author, dtype: int64

In [120]:
# Checking null values
reci.isnull().sum()

Recipe_name          0
Author               0
Date_published       0
Category             0
Cuisine           3313
Prep_time            0
Cook_time            0
Serving              0
Yield                0
Nutrition            0
Quantity             0
Unit                 0
Ingredient           0
dtype: int64

In [121]:
reci.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36735 entries, 0 to 36734
Data columns (total 13 columns):
Recipe_name       36735 non-null object
Author            36735 non-null object
Date_published    36735 non-null object
Category          36735 non-null object
Cuisine           33422 non-null object
Prep_time         36735 non-null object
Cook_time         36735 non-null object
Serving           36735 non-null object
Yield             36735 non-null object
Nutrition         36735 non-null object
Quantity          36735 non-null object
Unit              36735 non-null object
Ingredient        36735 non-null object
dtypes: object(13)
memory usage: 3.6+ MB


In [122]:
# Extracting Year column from Date_Published column
reci['Year']=reci.Date_published.apply(lambda x:x.split('-')[0])

In [123]:
reci.Year.value_counts()

2016    20668
2017    14861
2018     1206
Name: Year, dtype: int64

In [124]:
#Cleaning Ingredient column removing special characters
ing=[]
for i in reci.Ingredient:
    s=''
    for j in i:
        if(j.isalpha() or j==' '):
            s+=j
    ing.append(s)

In [125]:
ing[:10]

['walnuts',
 'spring onions',
 'white wine vinegar',
 'lettuce looseleaf',
 'garam masala powder',
 'salt',
 'strawberry',
 'mayonnaise',
 'onion',
 'chicken breasts']

In [126]:
# Putting modified ingredient content in original DataFrame
reci['Ingredient']=ing

In [127]:
# Cleaning Unit column removing special characters
unit=[]
for i in reci.Unit:
    s=''
    for j in i:
        if(j.isalpha() or j==' '):
            s+=j
    unit.append(s)

In [128]:
unit[:10]

['tablespoon',
 'Numbers',
 'tablespoon',
 'handful',
 'teaspoon',
 'pinch',
 'cup',
 'cup',
 'cup',
 'cup']

In [129]:
# Putting modified unit content in original DataFrame
reci['Unit']=unit

In [130]:
reci.head()

Recipe_name Author             Date_published  \
0  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
1  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
2  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
3  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
4  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   

  Category      Cuisine Prep_time Cook_time     Serving   Yield Nutrition  \
0   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   
1   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   
2   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   
3   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   
4   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   

  Quantity        Unit           Ingredient  Year  
0    ['2']  tablespoon              walnuts  2016  
1    ['3']     Numbers        spring onions  2016  
2    ['1']  tablespoon   white wine vinegar  2016  
3    ['1']     handful    lettuce looseleaf  2016  
4  ['1/4']    teaspoon  garam masala powder  2016

In [131]:
#Easier way to get rid of special characters in Quantity Column
reci.Quantity=reci.Quantity.str.replace("[",'')
reci.Quantity=reci.Quantity.str.replace("]",'')
reci.Quantity=reci.Quantity.str.replace("'",'')
reci.Quantity=reci.Quantity.str.replace("'",'')

In [132]:
reci.Quantity.value_counts()

1        10436
2         6759
1/2       4878
4         2095
1/4       1893
3         1678
0         1120
1 1/2      747
5          643
6          608
100        567
10         498
8          366
50         362
250        350
200        318
500        276
3/4        241
20         196
30         186
400        181
15         163
150        159
2 1/2      156
1/3        135
125        131
60         129
300        125
7          113
1/8         94
         ...  
3 1/4        1
439          1
4.0          1
635          1
460          1
390          1
128          1
578          1
1250         1
32           1
0.2          1
355          1
410          1
118          1
650          1
440          1
28           1
560          1
13           1
255          1
62           1
59           1
370          1
155          1
26           1
4 1/4        1
470          1
227          1
245          1
98           1
Name: Quantity, Length: 127, dtype: int64

In [133]:
# Converting fraction values ands value with fractions in floats
a=[]
b=[]
for i in reci.Quantity:
    if ('/') in i:
        if (' ') in i:
            n=i.split(' ')
            num,deno=n[1].split('/')
            n1=n[0]
            s=(float(num)/float(deno))+float(n1)
            a.append(round(s,2))
        else:
            num,deno=i.split('/')
            s=float(num)/float(deno)
            a.append(round(s,2))
    else:
        if(i.isdigit()):
            a.append(float(i))
        else:
            a.append(1)

In [134]:
len(a)

36735

In [135]:
# Putting modified quantity content in original DataFrame
reci['Quantity']=a

In [136]:
reci.head()

Recipe_name Author             Date_published  \
0  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
1  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
2  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
3  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
4  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   

  Category      Cuisine Prep_time Cook_time     Serving   Yield Nutrition  \
0   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   
1   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   
2   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   
3   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   
4   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl   352 cal   

   Quantity        Unit           Ingredient  Year  
0      2.00  tablespoon              walnuts  2016  
1      3.00     Numbers        spring onions  2016  
2      1.00  tablespoon   white wine vinegar  2016  
3      1.00     handful    lettuce looseleaf  2016  
4      0.25    teaspoon  garam masala powder  2016

In [137]:
# Cleaning nutrition column
reci.Nutrition=reci.Nutrition.str.replace(' cal','')

In [138]:
reci.head()

Recipe_name Author             Date_published  \
0  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
1  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
2  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
3  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   
4  Chicken and Strawberry Salad Recipe    TNN  2016-08-28T16:00:47+05:30   

  Category      Cuisine Prep_time Cook_time     Serving   Yield Nutrition  \
0   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl       352   
1   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl       352   
2   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl       352   
3   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl       352   
4   Salads  Continental     PT10M     PT20M  4 Servings  1 bowl       352   

   Quantity        Unit           Ingredient  Year  
0      2.00  tablespoon              walnuts  2016  
1      3.00     Numbers        spring onions  2016  
2      1.00  tablespoon   white wine vinegar  2016  
3      1.00     handful    lettuce looseleaf  2016  
4      0.25    teaspoon  garam masala powder  2016

In [139]:
nut=[]
for i in reci.Nutrition:
    if(i==''):
        pass
    else:
        nut.append(int(i))

In [140]:
np.mean(a)

21.181745746563223

In [141]:
#implementing empty values in nutrition
nut1=[]
for i in reci.Nutrition:
    if(i==''):
        nut1.append(356.44)
    else:
        nut1.append(float(i))

In [142]:
#Putting modified values in original DataFrame
reci.Nutrition=nut1

In [143]:
reci.Serving.value_counts()

4 Servings     10111
2 Servings      5675
6 Servings      4322
5 Servings      3865
 Servings       3297
8 Servings      3095
3 Servings      2641
10 Servings     1574
7 Servings       610
1 Servings       546
12 Servings      363
15 Servings      315
20 Servings      147
16 Servings       42
9 Servings        37
14 Servings       29
11 Servings       28
13 Servings       17
17 Servings       16
18 Servings        5
Name: Serving, dtype: int64

In [144]:
#Cleaning Servings
reci.Serving=reci.Serving.str.replace(' Servings','')

In [145]:
a=[]
for i in reci.Serving:
    if(i.isdigit()):
        a.append(int(i))

In [146]:
np.mean(a)

4.922931993540283

In [147]:
# Imputing empty values in Serving
serv=[]
for i in reci.Serving:
    if(i.isdigit()):
        serv.append(float(i))
    else:
        serv.append(4.92)

In [148]:
# Putting modified Serving column in DataFrame
reci.Serving=serv

In [149]:
reci.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36735 entries, 0 to 36734
Data columns (total 14 columns):
Recipe_name       36735 non-null object
Author            36735 non-null object
Date_published    36735 non-null object
Category          36735 non-null object
Cuisine           33422 non-null object
Prep_time         36735 non-null object
Cook_time         36735 non-null object
Serving           36735 non-null float64
Yield             36735 non-null object
Nutrition         36735 non-null float64
Quantity          36735 non-null float64
Unit              36735 non-null object
Ingredient        36735 non-null object
Year              36735 non-null object
dtypes: float64(3), object(11)
memory usage: 3.9+ MB


In [150]:
reci.Cook_time.value_counts()

PT30M     5468
PT40M     4562
PT25M     3762
PT35M     3714
PTNaNM    3353
PT20M     2881
PT45M     2541
PT50M     2226
PT60M     1894
PT70M     1267
PT55M     1092
PT15M      995
PT80M      767
PT65M      584
PT75M      326
PT90M      194
PT10M      176
PT140M     139
PT28M      119
PT130M      71
PT17M       67
PT100M      55
PT54M       48
PT135M      42
PT95M       34
PT85M       33
PT110M      31
PT145M      30
PT275M      28
PT22M       27
PT68M       26
PT59M       22
PT27M       21
PT56M       18
PT33M       15
PT105M      15
PT225M      12
PT18M       12
PT120M      12
PT195M      11
PT49M        8
PT37M        8
PT7M         7
PT150M       7
PT14M        6
PT5M         6
PT330M       3
Name: Cook_time, dtype: int64

In [151]:
# Cleaning Cook Time
reci.Cook_time=reci.Cook_time.str.replace('PT','')
reci.Cook_time=reci.Cook_time.str.replace('M','')

In [152]:
reci.Cook_time=reci.Cook_time.astype('float')

In [153]:
reci.isnull().sum()

Recipe_name          0
Author               0
Date_published       0
Category             0
Cuisine           3313
Prep_time            0
Cook_time         3353
Serving              0
Yield                0
Nutrition            0
Quantity             0
Unit                 0
Ingredient           0
Year                 0
dtype: int64

In [154]:
reci.Cook_time.mean()

40.717901863279614

In [155]:
# Imputing Cook Time
reci.Cook_time.fillna(value=40.71,inplace=True)

In [156]:
reci.isnull().sum()

Recipe_name          0
Author               0
Date_published       0
Category             0
Cuisine           3313
Prep_time            0
Cook_time            0
Serving              0
Yield                0
Nutrition            0
Quantity             0
Unit                 0
Ingredient           0
Year                 0
dtype: int64

In [157]:
reci.Prep_time.value_counts()

PT10M     12335
PT15M      9694
PT20M      6230
PTM        3313
PT5M       1904
PT30M      1574
PT25M       663
PT40M       249
PT60M       153
PT35M       136
PT45M        81
PT90M        62
PT50M        60
PT14M        48
PT65M        46
PT10-M       40
PT8M         30
PT120M       24
PT75M        22
PT55M        19
PT26M        18
PT13M        15
PT3M          8
PT2M          7
PT12M         4
Name: Prep_time, dtype: int64

In [158]:
# CLeaning Prep Time
reci.Prep_time=reci.Prep_time.str.replace('PT','')
reci.Prep_time=reci.Prep_time.str.replace('M','')
reci.Prep_time=reci.Prep_time.str.replace('-','')

In [159]:

ppt=[]
for i in reci.Prep_time:
    if(i.isdigit()):
        ppt.append(float(i))
    else:
        ppt.append(np.nan)

In [160]:
# Putting modified prep time in original dataframe
reci.Prep_time=ppt

In [161]:
reci.Prep_time.mean()

15.361917299982048

In [162]:
reci.isnull().sum()

Recipe_name          0
Author               0
Date_published       0
Category             0
Cuisine           3313
Prep_time         3313
Cook_time            0
Serving              0
Yield                0
Nutrition            0
Quantity             0
Unit                 0
Ingredient           0
Year                 0
dtype: int64

In [163]:
# Imputing null values
reci.Prep_time.fillna(value=15.36,inplace=True)

In [164]:
reci.Cuisine.value_counts()

North Indian     12466
Continental       4748
South Indian      3540
American          1957
Fusion            1665
Chinese           1617
Mughlai           1123
Italian            975
Mediterranean      817
Gujarati           602
Maharashtrian      573
Punjabi            548
Thai               491
Rajasthani         429
French             373
Bengali            331
Kashmiri           322
Mexican            215
Asian              143
Jain               140
North Eastern      108
Pakistani           61
Parsi               31
Sattvik             27
Indian              26
Goan                21
European            20
Spanish             15
Vietnamese          12
Turkish              9
Afghani              9
Fast food            8
Name: Cuisine, dtype: int64

In [165]:
# Imputing null values
reci.Cuisine.fillna('North Indian',inplace=True)

In [166]:
# COnverting all Ingredient values in lower case to avoid repetition
ing_new=[]
for i in reci.Ingredient:
    ing_new.append(i.lower())

In [167]:
reci.Ingredient=ing_new

In [168]:
reci.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36735 entries, 0 to 36734
Data columns (total 14 columns):
Recipe_name       36735 non-null object
Author            36735 non-null object
Date_published    36735 non-null object
Category          36735 non-null object
Cuisine           36735 non-null object
Prep_time         36735 non-null float64
Cook_time         36735 non-null float64
Serving           36735 non-null float64
Yield             36735 non-null object
Nutrition         36735 non-null float64
Quantity          36735 non-null float64
Unit              36735 non-null object
Ingredient        36735 non-null object
Year              36735 non-null object
dtypes: float64(5), object(9)
memory usage: 3.9+ MB


In [169]:
# Splitting Target and Predictors
x=reci.drop(['Recipe_name','Author','Date_published','Category','Yield'],axis=1)
y=reci.Category

In [170]:
dum_X=pd.get_dummies(x,drop_first=True)

In [171]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

In [172]:
# Scaling
scaled_x=pd.DataFrame(sc.fit_transform(dum_X),columns=dum_X.columns)

E:\Users\Soham Raut\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype uint8, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
E:\Users\Soham Raut\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype uint8, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [173]:
scaled_x.head()

Prep_time  Cook_time   Serving  Nutrition  Quantity  Cuisine_American  \
0   -0.63955  -1.048776 -0.353766  -0.024787 -0.244542         -0.237216   
1   -0.63955  -1.048776 -0.353766  -0.024787 -0.231793         -0.237216   
2   -0.63955  -1.048776 -0.353766  -0.024787 -0.257291         -0.237216   
3   -0.63955  -1.048776 -0.353766  -0.024787 -0.257291         -0.237216   
4   -0.63955  -1.048776 -0.353766  -0.024787 -0.266852         -0.237216   

   Cuisine_Asian  Cuisine_Bengali  Cuisine_Chinese  Cuisine_Continental  \
0      -0.062514        -0.095354         -0.21458             2.595562   
1      -0.062514        -0.095354         -0.21458             2.595562   
2      -0.062514        -0.095354         -0.21458             2.595562   
3      -0.062514        -0.095354         -0.21458             2.595562   
4      -0.062514        -0.095354         -0.21458             2.595562   

     ...      Ingredient_yellow moong dal  Ingredient_yellow onion  \
0    ...                        -0.009037                -0.005218   
1    ...                        -0.009037                -0.005218   
2    ...                        -0.009037                -0.005218   
3    ...                        -0.009037                -0.005218   
4    ...                        -0.009037                -0.005218   

   Ingredient_yellow pepper  Ingredient_yellow tomato  Ingredient_yellow yam  \
0                 -0.015654                 -0.005218              -0.005218   
1                 -0.015654                 -0.005218              -0.005218   
2                 -0.015654                 -0.005218              -0.005218   
3                 -0.015654                 -0.005218              -0.005218   
4                 -0.015654                 -0.005218              -0.005218   

   Ingredient_yellow zucchini  Ingredient_yoghurt curd  Ingredient_zucchini  \
0                   -0.005218                -0.112486            -0.017307   
1                   -0.005218                -0.112486            -0.017307   
2                   -0.005218                -0.112486            -0.017307   
3                   -0.005218                -0.112486            -0.017307   
4                   -0.005218                -0.112486            -0.017307   

   Year_2017  Year_2018  
0  -0.824252  -0.184239  
1  -0.824252  -0.184239  
2  -0.824252  -0.184239  
3  -0.824252  -0.184239  
4  -0.824252  -0.184239  

[5 rows x 1103 columns]

In [174]:
#Splitting in train set and test set
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(scaled_x,y,test_size=0.3,random_state=10)

In [175]:
# Aplying Decision Tree
from sklearn.tree import DecisionTreeClassifier

dt=DecisionTreeClassifier(max_depth=24)

pred_dt=dt.fit(x_train,y_train).predict(x_test)

print('Training Score:-')
print(dt.score(x_train,y_train))
print('Testing Score:-')
print(dt.score(x_test,y_test))
print('Cohen Kappa Score')
print(cohen_kappa_score(pred_dt,y_test))

Training Score:-
0.9906276736408183
Testing Score:-
0.9813084112149533
Cohen Kappa Score
0.9770549023418993


In [176]:
from sklearn.model_selection import GridSearchCV

In [177]:
#Optimal value for max_depth
params={'max_depth':np.arange(1,25)}

model_grid=GridSearchCV(dt,params,cv=5)
model_grid.fit(x_train,y_train)
print(model_grid.best_score_)
print(model_grid.best_params_)

E:\Users\Soham Raut\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


0.9647273858598429
{'max_depth': 24}


In [178]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(pred_dt,y_test))

[[3512    9    7    0    4   13    0   10    1    0    7   21    0]
 [  11  690    0    0    5    0    1    2    2    0    4    1    0]
 [   0    0  230    0    2    0    0    0    0    0    0    0    0]
 [   0    0    0   84    0    0    0    0    0    0    0    0    0]
 [  10    0    0    0  884    0    0    0    0    0    0    0    0]
 [   2    0    0    0    0  769    0    2    0    0    0    1    0]
 [   0    0    0    0    0    0   51    0    0    0    0    0    0]
 [  25   11    0    0    2    5    0 2006    0    0    2   20    0]
 [   4    5    0    0    0    0    0    0  192    0    0    2    0]
 [   0    0    0    0    0    0    0    0    0   46    0    0    0]
 [   0    0    0    0    2    0    0    0    0    0  608    0    0]
 [   6    1    0    0    6    0    0    0    0    0    0 1738    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    5]]


In [179]:
# Applying Rabdom forest 
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(max_depth=24)

In [180]:
pred=rf.fit(x_train,y_train).predict(x_test)

E:\Users\Soham Raut\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [181]:
from sklearn.metrics import accuracy_score,cohen_kappa_score

In [182]:
print('Training Score:-')
print(rf.score(x_train,y_train))
print('Testing Score:-')
print(rf.score(x_test,y_test))
print('Cohen Kappa Score')
print(cohen_kappa_score(pred,y_test))

Training Score:-
0.7594306603406704
Testing Score:-
0.6627347790581617
Cohen Kappa Score
0.5607460176746806


In [183]:
# Boosting on Random Forest
from sklearn.ensemble import AdaBoostClassifier

ada=AdaBoostClassifier(base_estimator=rf)

pred_ad=ada.fit(x_train,y_train).predict(x_test)



In [184]:
print('Training Score:-')
print(ada.score(x_train,y_train))
print('Testing Score:-')
print(ada.score(x_test,y_test))
print('Cohen Kappa Score')
print(cohen_kappa_score(pred_ad,y_test))

Training Score:-
0.9923776930854787
Testing Score:-
0.7983849015515834
Cohen Kappa Score
0.7453388059745263
